"use client";

import { motion } from "framer-motion";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-bg">
      <Header />
      
      <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-6 py-12 flex flex-col gap-10">
        <motion.div 
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className="text-center sm:text-left border-b border-border pb-6"
        >
          <h1 className="text-xl sm:text-2xl font-bold text-text-primary tracking-tight font-sans">
            Terms & Conditions
          </h1>
          <p className="text-xs sm:text-sm text-text-secondary mt-2 leading-relaxed max-w-2xl font-sans">
            Effective Date: July 19, 2026. Please read these Terms of Service carefully before utilizing the Decimal Lens validation pipeline.
          </p>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.4, delay: 0.05 }}
          className="bg-panel border border-border rounded-lg p-6 sm:p-8 shadow-sm flex flex-col gap-6 text-xs text-text-secondary leading-relaxed font-sans"
        >
          <section className="flex flex-col gap-2">
            <h3 className="text-sm font-bold text-text-primary">
              1. Acceptance of Terms
            </h3>
            <p>
              By accessing or using the Decimal Lens platform, you agree to be bound by these terms. If you do not agree, you are prohibited from using the application to verify financial reports.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h3 className="text-sm font-bold text-text-primary">
              2. Financial Analysis & Non-Reliance Disclaimer
            </h3>
            <p>
              <strong>IMPORTANT NOTICE:</strong> Decimal Lens provides automated, dual-agent quantitative claims auditing and mathematical verification tools. It does NOT provide certified investment, financial, tax, or legal advice. 
            </p>
            <p>
              All 3-year growth projections, operating margin calculations, and risk weights generated by the Forecaster Agent are speculative models based on the semantic parsing of uploaded filings. You must independently audit all metrics and recalculated math before making commercial, investment, or regulatory decisions. Decimal Lens assumes no liability for trading losses, reporting errors, or quantitative model reliance.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h3 className="text-sm font-bold text-text-primary">
              3. Service Limitations & Security Bounds
            </h3>
            <p>
              Decimal Lens provides arithmetic verification on a best-efforts basis. While our interval-arithmetic HULP engine scales verification tolerances to check rounding accumulation errors, we do not guarantee 100% extraction completeness of all footnoted formulas in complex, multi-statement reports.
            </p>
            <p>
              Users are responsible for ensuring that uploaded documents do not contain restricted, unreleased, or inside corporate information that violates compliance protocols.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h3 className="text-sm font-bold text-text-primary">
              4. Governing Law
            </h3>
            <p>
              These Terms of Service shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles.
            </p>
          </section>
        </motion.div>
      </main>

      <Footer />
    </div>
  );
}
